### PR TITLE
smaller fake PNG image for testing

### PR DESCRIPTION
**Pull request by jewlofthelotus**
Hey @albertbellonch - I just copied the image you had already been using for tests and changed the extension on it. Cuts down significantly, so that should work out - but let me know if you want to try something else.

Thanks for letting me contribute!

### CODE REVIEW

**Comment by albertbellonch** [comment]
Hi @jewlofthelotus,

Thanks you for contributing, not the other way round :D

I suggest you investigate how to bundle only production-oriented stuff in gems. As I said, the testing suite (and therefore, in this case, the images we use for testing) should not be bundled inside the gem, because only the `lib/` code (speaking generically) will be used. There must be a way to do this in a clean way.

This way we both learn something new :)

**Comment by jewlofthelotus** [comment]
Hey @albertbellonch - unfortunately, I just don't have the time to research and implement the ideal solution.  This change improves package size significantly - so take it or leave it. Sorry I can't be of more help at this time.

**Comment by albertbellonch** [comment]
Hi @jewlofthelotus, it's OK for now, I'll merge and release a new version.

Bonus points for improving it in the future :)

Thanks!

**Comment by albertbellonch** [comment]
PS. Piet 0.2.2 released [here](https://rubygems.org/gems/piet/versions/0.2.2).

**Pull request merged**
