### PR TITLE
Doc/carrierwave integration with options

### PR DESCRIPTION
**Pull request by PikachuEXE**
For #29

### CODE REVIEW

**Comment by albertbellonch** [comment]
Hi @PikachuEXE,

Thanks for the work!

I'm not sure if the inclusion of IDEA files in the `.gitignore` file makes sense. Maybe we should revert it?

Best,

**Comment by PikachuEXE** [comment]
OK
But I think they should be excluded anyway (either in this branch or not)
Those project files store device specific setting/path etc.

**Comment by albertbellonch** [comment]
Hi @PikachuEXE,

Maybe it doesn't make sense to have a Java-specific IDE config files in a repository which is plain Ruby (with some external dependencies).

What do you think? Maybe we remove those files from `.gitignore`?

Best,

**Comment by PikachuEXE** [comment]
I think I type them wrong somehow
Should be `RubyMine` instead of `IDEA`

**Comment by PikachuEXE** [comment]
Commit messages & content changed

**Comment by albertbellonch** [comment]
Great, merging!

**Comment by PikachuEXE** [comment]
Thanks :D

**Pull request merged**
