### PR TITLE
CI for ruby 2.2, 2.3 and 2.4 / Drop ruby 1.9 from CI

### PR DESCRIPTION
**Pull request by toshimaru**
- Add ruby 2.2, 2.3 and 2.4 to TravisCI
- Remove Gemfile.lcok file. Use gemfile instead.
- Drop ruby 1.9 from TravisCI since most dependency gems require ruby 2.0+.

### CODE REVIEW

**Comment by albertbellonch** [comment]
Hi @toshimaru,

Thanks for your work!

It's great to add more supported Ruby versions, as well as removing 1.9.3 (which has been obsolete for almost a year already). 

Nevertheless, I'm not sure why should we drop `Gemfile.lock`. Why are you for this option?

Best,

**Comment by toshimaru** [comment]
Hello, @albertbellonch,

> Why are you for this option?

I omitted `Gemfile.lock` because I'd like to test latest gem versions.

Gems are installed depending on `Gemfile`(gemspec), so if I run `bundle install` now, current latest versions which meet gemspec's requirement will be installed. If you have lock file in repo, yes, you can lock the version, but the versions are outdated.

But there's still a problem. ActiveSupport 5 is not compatible with either Ruby 2.0 or 2.1. So I used `gemfiles/activesupport-4.gemfile` for Ruby2.0/2.1 and excluded those cases from CI.

build__9_-_toshimaru_piet_-_travis_ci

FWI, `bundle gem` ignores `Gemfile.lock` by default. (Although I don't know behavior in old bundler version ;) )

see. https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/gitignore.tt

**Comment by albertbellonch** [comment]
Hi @toshimaru,

Again, thanks a lot for your work! Sorry for answering this late.

I'm merging now and will release Piet 0.2.5 in a few minutes.

Best,

**Comment by albertbellonch** [comment]
[Here it is](https://rubygems.org/gems/piet/versions/0.2.5)!

**Comment by albertbellonch** [comment]
[Here it is](https://rubygems.org/gems/piet/versions/0.2.5)! cc @toshimaru

**Comment by toshimaru** [comment]
<3

**Pull request merged**
