### PR TITLE
optimize based on MIME type rather than file extension

### PR DESCRIPTION
**Pull request by jewlofthelotus**
Switched out file extension detection for MIME type detection, which should be a bit more reliable. 

This is a good demo image to test with - it's got a `.png` extension but actually has JPEG image data.

Hope this helps!

### CODE REVIEW

**Comment by albertbellonch** [comment]
Hi @jewlofthelotus,

Thanks a lot for your work! I really like this solution because it's a bit more elegant, as it is not extension-dependant.

Could you please add a few specs so we can be sure that this works perfectly? It would be nice to have both images correctly labeled (e.g. JPGs as JPGs) and incorrectly too (e.g. PNGs as JPGs, like this one that you add to the PR).

I'll merge and push a new version when you have them ready.

Best!

**Comment by albertbellonch** [comment]
Hi @jewlofthelotus,

That is perfect! Thank you so much for your work.

I'll merge and release a new version now.

Cheers!

**Comment by albertbellonch** [comment]
Hi @jewlofthelotus,

New version already available in [Rubygems](https://rubygems.org/gems/piet).

I just realized, though, that the image you added has significantly increased the gem size.

Any idea on how to avoid this? The testing suite should not affect the bundled gem, either dependency or size wise.

Thanks,

**Comment by jewlofthelotus** [comment]
@albertbellonch good call! I'll swap out some images and submit another PR tomorrow.

**Comment by albertbellonch** [comment]
@jewlofthelotus Perfect then! I think we should be able to maintain the images we have but, since they are only used in testing, they should not be in the bundled gem. I don't know exactly how to do it, but t should not be difficult.

**Pull request merged**
