### PR TITLE
close io after reading

### PR DESCRIPTION
**Pull request by lavrovdv**

### CODE REVIEW

**Comment by lavrovdv** [comment]
This branch passing in my travis build https://travis-ci.org/lavrovdv/piet/builds/110717290

**Comment by albertbellonch** [comment]
Hi @lavrovdv,

The build is still failing in Travis :(

Do you know if they are having some kind of problem?

**Comment by albertbellonch** [comment]
Hi @lavrovdv,

Did you solve the issue? Looks like the build passed after you last commit.

Best,

**Comment by lavrovdv** [comment]
Hi @albertbellonch, bundler update solved the issue with travis.

**Pull request closed without merging**
